### ISSUE TITLE
[BUG] Not working on NixOS

### ISSUE THREAD

**Issue by inkstray** [SpiralP/classicube-cef-loader-plugin#19]
- I get the following error: (most likely due to NixOS storing files differently)
```DEBUG Init classicube-cef-loader-plugin v1.3.7
DEBUG dll_load ./cef/classicube_cef_linux_x86_64.so
ERROR Error(
    Msg(
        "libgobject-2.0.so.0: cannot open shared object file: No such file or directory",
    ),
    State {
        next_error: None,
        backtrace: InternalBacktrace {
            backtrace: None,
        },
    },
)
 INFO &cCouldn't load cef plugin: &flibgobject-2.0.so.0: cannot open shared object file: No such file or directory
```
probably cant find due to nixos using
```/nix/store/7fg5lvqxx3wrgj74c5xljyil1d0ah7n8-glib-2.78.4/lib/libgobject-2.0.so.0```
instead of /usr/lib directory

**Comment by SpiralP** [comment]
@inkstray i just pushed a branch that probably works on nixos
```
nix build --print-build-logs github:SpiralP/classicube-cef-plugin/nixos
rm -rf cef
cp -va result/* .
chmod -R u+w cef plugins
```

i normally run classicube (on nixos) in flatpak or other FHS envs because it's easier to use plugins on a normal debian/ubuntu linux


also this repo (cef-loader-plugin) is for the loader, which downloads the "normal" linux library files without patching them for nix

i pushed that nixos branch to the real cef repo [here](https://github.com/SpiralP/classicube-cef-plugin/tree/nixos) and might eventually get it into master (i have to test on all the other OS's since they're probably broken now)
